#!/bin/bash

##Note alternatively you can add an alias to your ~/.bashrc file
# alias branch='git branch --show-current'
# Then source the bashrc file or logout and log back in
# source ~/.bashrc
# then you can just run
# git push/pull origin $(branch)
# and it'll grab the current branch and push or pull it
# You can also create this alias using a function
#alias get='f() { git "$1" origin "$(git branch --show-current)"; unset -f f; }; f'

# Check if the first argument is empty.
if [ -z "$1" ]; then
    echo "Error: Need input argument that says 'push' or 'pull'"
    exit 1
fi


#Echo the inputs from the user
DIRECTION=$1

echo 'You are choosing to ' $DIRECTION

#run git branch to find out the branch name and save that to a variable
BRANCHNAME=$(git branch --show-current)

echo 'The branch name is ' $BRANCHNAME

#Then push or pull from that branch name
echo 'git' $DIRECTION 'origin' $BRANCHNAME
git $DIRECTION origin $BRANCHNAME
