#!/bin/bash

echo 'Converting File:' $1
filename=${1%.pdf}
echo 'File without .pdf:' $filename
echo 'New Filename:' ${filename}_encryted.pdf
echo 'Please Type in your password'
read -p "?" password
#echo 'Password: ' $password

pdftk $1 output ${filename}_encrypted.pdf user_pw $password encrypt_128bit 
