#!/bin/bash

if [ -e "$1.pdf" ]; then
    echo "Converting file to Jpg..."
    convert -density $2 $1.pdf $1.jpg
    echo "File Converted"
else
   echo $1.pdf
   echo "does not exist"
fi
# Copyright - Carlos Montalvo 2015
# You may freely distribute this file but please keep my name in here
# as the original owner
