#!/bin/bash

for file in *;
do
  echo "Converting File = " $file
  convert $file $file.tiff
done

# Copyright - Carlos Montalvo 2015
# You may freely distribute this file but please keep my name in here
# as the original owner
