#!/bin/bash

#FOr more inspiration read this
#https://www.internalpointers.com/post/convert-vob-files-mkv-ffmpeg

##FIrst use brasero and make a clean copy of the dvd to an ISO. Then, mount the ISO to your computer and use this utility to copy all VOBs to your desktop and then convert them to mp4 for further procesing
##You can't copy the VOBs directly from the ISO because they are locked for read only. So you need to copy them to your desktop first using brasero and make the clean ISO copy.

#NAME=
#DIR=/run/user/1000/gvfs/archive:host=file%253A%252F%252F%252Fhome%252Fantec%252FDesktop%252F$NAME.iso

FILES=$(ls $DIR/VIDEO_TS/*.VOB)

##MAKE THE DVD DIR
mkdir DVD

###COPY FILE TO DESKTOP
for VAR in $FILES
do
    FILENAME=$(basename "$VAR")
    echo 'Copying to computer: ' $FILENAME 
    rsync -ah --info=progress2 $VAR DVD/$FILENAME
done

##CONVERT ALL VOB to MP4
for VAR in $FILES
do
    filename=$(basename -- "$VAR")
    extension="${filename##*.}"
    filename_no_ext="${filename%.*}"
    echo 'Converting ' $filename ' to: ' $filename_no_ext.mp4
    ffmpeg -i DVD/$filename -c copy DVD/$filename_no_ext.mp4
done

mkdir DVD/VOBs
mkdir DVD/MP4s
mv DVD/*.mp4 DVD/MP4s
mv DVD/*.VOB DVD/VOBs

##After this you need to prune the conversion and only save the VOBs/MP4s that you want
##ONce you have the remaining VOBs that matter you run the following command
# cat *.VOB > output.VOB
# which will concatenate the entire VOB as one cohesive unit
# then you run this to convert
# ffmpeg -i output.VOB output.mp4
