#!/bin/bash

for oldfile in $1/*.$2; do
    echo $oldfile
    newfile="$oldfile"_compressed.jpg
    echo $newfile
    convert -verbose -resize 50% $oldfile $newfile
done

#convert -verbose -resize 50% Convert_Files/Papi2_1.jpeg /Users/carlos/Desktop/Papi2_1_compressed.png
# Copyright - Carlos Montalvo 2015
# You may freely distribute this file but please keep my name in here
# as the original owner
