#!/bin/bash


echo 'Searching for file: ' $1
USER=$(whoami)
find /home/$USER -name $1 -exec cat {} \;

# Copyright - Carlos Montalvo 2015
# You may freely distribute this file but please keep my name in here
# as the original owner
