#!/bin/bash


echo 'Searching for file: ' $1

find /home/carlos -name $1 -exec cat {} \;

# Copyright - Carlos Montalvo 2015
# You may freely distribute this file but please keep my name in here
# as the original owner
