#!/bin/bash

file=$1

if [ -e "$file" ]; then
    #get name of file minus .tar.gz
    size=${#file}
    endpt=$(($size - 7))
    one=0
    filename=${file:$one:$endpt}
    
    #gunzip first
    gunzip $filename.tar.gz
    #untar file
    tar -xvf $filename.tar
else
    echo 'File does not exist' $file
fi




# Copyright - Carlos Montalvo 2015
# You may freely distribute this file but please keep my name in here
# as the original owner
